# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
"""Python interface to the UniPlot pure-Nim plotting engine."""
from ._core import (
    AXIS_DURATION,
    AXIS_NUMERIC,
    AXIS_UTC_DATETIME,
    AGG_COUNT,
    AGG_MAXIMUM,
    AGG_MEAN,
    AGG_MINIMUM,
    AGG_SUM,
    COORD_CARTESIAN,
    COORD_POLAR,
    HISTOGRAM_AUTO,
    HISTOGRAM_FREEDMAN_DIACONIS,
    HISTOGRAM_RICE,
    HISTOGRAM_SCOTT,
    HISTOGRAM_SQUARE_ROOT,
    HISTOGRAM_STURGES,
    LINE_DASHED,
    LINE_DOT_DASH,
    LINE_DOTTED,
    LINE_LONG_DASH,
    LINE_SOLID,
    MARKER_CIRCLE,
    MARKER_CROSS,
    MARKER_DIAMOND,
    MARKER_PLUS,
    MARKER_SQUARE,
    MARKER_TRIANGLE,
    MISSING_BREAK,
    MISSING_DROP,
    MISSING_REJECT,
    RASTER_BILINEAR,
    RASTER_BOX,
    RASTER_NEAREST,
    SCALE_LINEAR,
    SCALE_LOG10,
    SCALE_POWER,
    SCALE_SYMLOG10,
    Plot,
    abi_version,
    facet_png,
    facet_svg,
    facet_matrix_png,
    facet_matrix_svg,
    grid_png,
    grid_svg,
    version,
)

__version__ = version()
__all__ = [
    "AXIS_DURATION", "AXIS_NUMERIC", "AXIS_UTC_DATETIME",
    "AGG_COUNT", "AGG_MAXIMUM", "AGG_MEAN", "AGG_MINIMUM", "AGG_SUM",
    "COORD_CARTESIAN", "COORD_POLAR",
    "HISTOGRAM_AUTO", "HISTOGRAM_FREEDMAN_DIACONIS", "HISTOGRAM_RICE",
    "HISTOGRAM_SCOTT", "HISTOGRAM_SQUARE_ROOT", "HISTOGRAM_STURGES",
    "LINE_DASHED", "LINE_DOT_DASH", "LINE_DOTTED", "LINE_LONG_DASH",
    "LINE_SOLID", "MARKER_CIRCLE", "MARKER_CROSS", "MARKER_DIAMOND",
    "MARKER_PLUS", "MARKER_SQUARE", "MARKER_TRIANGLE", "Plot",
    "MISSING_BREAK", "MISSING_DROP", "MISSING_REJECT",
    "RASTER_BILINEAR", "RASTER_BOX", "RASTER_NEAREST",
    "SCALE_LINEAR", "SCALE_LOG10", "SCALE_POWER", "SCALE_SYMLOG10",
    "abi_version", "facet_matrix_png", "facet_matrix_svg", "facet_png",
    "facet_svg", "grid_png", "grid_svg", "version", "__version__",
]
